"""Initial migration

Revision ID: 1e1b206ff896
Revises: 
Create Date: 2024-01-22 20:43:35.074968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e1b206ff896'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'expenses', ['id'])
    op.add_column('trips', sa.Column('budget', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'trips', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='unique')
    op.drop_column('trips', 'budget')
    op.drop_constraint(None, 'expenses', type_='unique')
    # ### end Alembic commands ###
