"""Add is_email_verified to users

Revision ID: 51474146c9ba
Revises: 1e1b206ff896
Create Date: 2024-01-27 17:11:07.629319

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51474146c9ba'
down_revision = '1e1b206ff896'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
